from day08 import Coordinate, Day08Puzzle


def test_first_example():
    input = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
.........."""
    puzzle = Day08Puzzle(input)
    antinodes = puzzle.find_antinodes(
        Coordinate(4, 3),
        Coordinate(5, 5),
    )
    expected = {Coordinate(3, 1), Coordinate(6, 7)}
    assert antinodes == expected
